In [1]:
import pandas as pd
from pathlib import Path
from concurrent.futures import ThreadPoolExecutor
from functools import partial
import cv2
from tqdm import tqdm

In [2]:
from sample_frames_ecc import ecc_warp, choose_metric_size

In [3]:
frames = list(Path("/home/roman/ba/niederfuellbach2_autos/frames/mercedes_a_class_orbit_frames_1_sdr").glob("*.png"))

In [4]:
pairs = list(zip(frames,frames[1:]))

In [5]:
metric_wh = choose_metric_size(
    first_frame_bgr=cv2.imread(frames[0]),
    target_w=960,
    target_h=540,
)

In [6]:
ecc_fn = partial(
    ecc_warp,
    model="homography",
    metric_wh=metric_wh,
)

In [8]:
with ThreadPoolExecutor() as executor:
    ecc_dist = list(tqdm(executor.map(ecc_fn, pairs), total=len(pairs)))

100%|██████████| 14426/14426 [33:05<00:00,  7.27it/s]

In [11]:
ecc_dist

[0.6961519718170166,
 0.8087875843048096,
 0.7927371263504028,
 0.8430817127227783,
 0.8589888215065002,
 0.917831540107727,
 0.8878285884857178,
 0.8401846289634705,
 0.6817516684532166,
 0.5775970220565796,
 0.5164409875869751,
 0.5961577892303467,
 0.766461968421936,
 0.8353706002235413,
 1.0233314037322998,
 1.1405762434005737,
 1.234168291091919,
 1.2642285823822021,
 1.1831691265106201,
 1.1765117645263672,
 1.0758614540100098,
 0.887202262878418,
 0.7665752172470093,
 0.6686540842056274,
 0.7191393971443176,
 0.8490639925003052,
 0.9055521488189697,
 0.8515249490737915,
 0.821715772151947,
 0.7856708765029907,
 0.8401279449462891,
 0.767518162727356,
 0.720835268497467,
 0.7265685796737671,
 0.7312461137771606,
 0.7869759798049927,
 0.9630367159843445,
 1.1504783630371094,
 1.3670402765274048,
 1.493293285369873,
 1.615232229232788,
 1.7305326461791992,
 1.8436918258666992,
 2.162283182144165,
 2.4953079223632812,
 5.037310600280762,
 5.557880401611328,
 5.630001544952393,
 5.3870744705200195,
 5.0457329750061035,
 4.6568708419799805,
 4.285465240478516,
 3.9277873039245605,
 3.5474071502685547,
 3.0992746353149414,
 2.6671271324157715,
 2.321593999862671,
 2.1712703704833984,
 2.162954807281494,
 2.0912556648254395,
 2.047123908996582,
 1.812090516090393,
 1.6908981800079346,
 1.6565974950790405,
 1.584075927734375,
 1.595339059829712,
 1.7657928466796875,
 2.1835074424743652,
 2.563599109649658,
 2.728768825531006,
 2.7948341369628906,
 2.8075296878814697,
 2.8239569664001465,
 2.947481393814087,
 2.934664249420166,
 2.9393301010131836,
 2.963202714920044,
 3.0436267852783203,
 3.110682725906372,
 3.059579849243164,
 2.9060468673706055,
 2.7987208366394043,
 2.607893943786621,
 2.5670886039733887,
 2.450650930404663,
 2.2599358558654785,
 1.9302067756652832,
 1.6554484367370605,
 1.4750909805297852,
 1.2152366638183594,
 1.090193271636963,
 0.8930414915084839,
 0.8123690485954285,
 0.7789621353149414,
 0.9020466804504395,
 0.9469914436340332,
 0.9293068647384644,
 0.9676975011825562,
 1.0082015991210938,
 1.1141104698181152,
 1.1482967138290405,
 1.312955379486084,
 1.499322772026062,
 1.5129938125610352,
 1.5576367378234863,
 1.4852372407913208,
 1.5018978118896484,
 1.4134764671325684,
 1.3528623580932617,
 1.3572006225585938,
 1.3114659786224365,
 1.3550071716308594,
 1.4143385887145996,
 1.457996129989624,
 1.4340698719024658,
 1.3936023712158203,
 1.37514328956604,
 1.2796587944030762,
 1.267106056213379,
 1.2083749771118164,
 1.1397960186004639,
 1.088088035583496,
 1.06172776222229,
 1.0667917728424072,
 1.0537540912628174,
 1.0587694644927979,
 1.0775123834609985,
 1.0701098442077637,
 1.1344566345214844,
 1.1902564764022827,
 1.2936699390411377,
 1.4821397066116333,
 1.6852688789367676,
 1.9320403337478638,
 2.0921730995178223,
 2.1676836013793945,
 2.2568979263305664,
 2.3541057109832764,
 2.9267630577087402,
 3.0947351455688477,
 2.955995559692383,
 2.7751693725585938,
 2.6399173736572266,
 2.5187089443206787,
 2.4819512367248535,
 2.3577866554260254,
 2.248502254486084,
 2.1752963066101074,
 2.1562700271606445,
 2.1269145011901855,
 1.9431381225585938,
 1.8127069473266602,
 1.7913100719451904,
 1.9698048830032349,
 2.1442365646362305,
 2.338878631591797,
 2.438943386077881,
 2.4248595237731934,
 2.3546297550201416,
 2.2923407554626465,
 2.2172677516937256,
 2.1865415573120117,
 1.9800302982330322,
 1.719710111618042,
 1.292783260345459,
 0.9987948536872864,
 0.848342776298523,
 0.7671689391136169,
 0.7764557600021362,
 0.7570672035217285,
 0.7693620920181274,
 0.8211989402770996,
 0.809409499168396,
 0.8337588310241699,
 0.8230900764465332,
 0.9251788854598999,
 1.03956937789917,
 1.1611590385437012,
 1.2402286529541016,
 1.2240386009216309,
 1.3628990650177002,
 1.4376581907272339,
 1.652248501777649,
 1.7831931114196777,
 1.8965576887130737,
 1.9993577003479004,
 2.030961513519287,
 1.9839026927947998,
 1.8515675067901611,
 1.610862374305725,
 1.4106616973876953,
 1.0564451217651367,
 0.935884952545166,
 0.8563470840454102,
 0.9375454187393188,
 1.003589153289795,
 0.9753454327583313,
 0.9148505926132202,
 0.9156981706619263,
 0.9806634187698364,
 1.1112756729125977,
 1.1777927875518799,
 1.230544090270996,
 1.2228217124938965,
 1.2772397994995117,
 1.3188509941101074,
 1.445497989654541,
 1.5033069849014282,
 1.5595827102661133,
 1.5666453838348389,
 1.5225028991699219,
 1.5214074850082397,
 1.4503326416015625,
 1.270708441734314,
 1.0739750862121582,
 0.9616546630859375,
 0.9043511748313904,
 0.8128184080123901,
 0.7920093536376953,
 0.8276040554046631,
 0.8098351359367371,
 0.7610881328582764,
 0.7734450101852417,
 0.774544358253479,
 0.8376781940460205,
 0.8373256921768188,
 0.8381870985031128,
 0.7846193313598633,
 0.7982659339904785,
 0.7442421913146973,
 0.7710539102554321,
 0.7151399850845337,
 0.7115508913993835,
 0.6958407163619995,
 0.7124251127243042,
 0.7078010439872742,
 0.7442848682403564,
 0.8028789162635803,
 0.853446364402771,
 0.941711962223053,
 0.9792901277542114,
 0.9365799427032471,
 0.8863619565963745,
 0.8375507593154907,
 0.8174606561660767,
 0.8053667545318604,
 0.8361495137214661,
 0.8474167585372925,
 0.9173547029495239,
 0.962169349193573,
 1.0065312385559082,
 1.0577802658081055,
 1.1531535387039185,
 1.2500851154327393,
 1.3303687572479248,
 1.403047800064087,
 1.516169786453247,
 1.5685834884643555,
 1.591832160949707,
 1.718825340270996,
 1.7768992185592651,
 1.8069820404052734,
 1.7468054294586182,
 1.7807939052581787,
 1.7977488040924072,
 1.7506098747253418,
 1.7356548309326172,
 1.7443886995315552,
 1.7222108840942383,
 1.669385552406311,
 1.4953769445419312,
 1.4677982330322266,
 1.4251694679260254,
 1.3204545974731445,
 1.1897456645965576,
 1.129636526107788,
 1.0088088512420654,
 0.9528840184211731,
 0.8972870111465454,
 0.8319958448410034,
 0.8508362770080566,
 0.789793848991394,
 0.7865703105926514,
 0.7545695304870605,
 0.7635498046875,
 0.7915982007980347,
 0.764146089553833,
 0.7802414894104004,
 0.8572326898574829,
 0.8750131130218506,
 0.8454157114028931,
 0.7892014980316162,
 0.7632900476455688,
 0.7447718381881714,
 0.7295060753822327,
 0.7745101451873779,
 0.7999963760375977,
 0.8421245217323303,
 0.8917845487594604,
 0.9093355536460876,
 0.9517253041267395,
 0.997164249420166,
 1.0339325666427612,
 1.140470266342163,
 1.2114208936691284,
 1.2157471179962158,
 1.1480753421783447,
 1.0441291332244873,
 0.9193213582038879,
 0.7908486723899841,
 0.7663103342056274,
 0.7891218066215515,
 0.7785659432411194,
 0.7995108962059021,
 0.8749892115592957,
 1.0226960182189941,
 1.120042324066162,
 1.2171077728271484,
 1.2880420684814453,
 1.2705934047698975,
 1.3371436595916748,
 1.3059139251708984,
 1.2169183492660522,
 1.1604194641113281,
 0.9863616228103638,
 0.9256726503372192,
 0.8904837965965271,
 0.8684074282646179,
 0.8939187526702881,
 0.9187180995941162,
 0.9516750574111938,
 0.9637153744697571,
 0.9944708347320557,
 1.027536392211914,
 1.093361258506775,
 1.144217848777771,
 1.3106772899627686,
 1.425732135772705,
 1.552004337310791,
 1.630631446838379,
 1.670414924621582,
 1.6741361618041992,
 1.6057679653167725,
 1.6543906927108765,
 1.6734144687652588,
 1.7485969066619873,
 1.5690573453903198,
 1.561561107635498,
 1.4995932579040527,
 1.475887417793274,
 1.5320844650268555,
 1.5130738019943237,
 1.511460542678833,
 1.4911442995071411,
 1.5011794567108154,
 1.5761053562164307,
 1.6240901947021484,
 1.6514586210250854,
 1.657219648361206,
 1.6348350048065186,
 1.6228652000427246,
 1.557399034500122,
 1.5466599464416504,
 1.5004990100860596,
 1.4602160453796387,
 1.3982043266296387,
 1.3433864116668701,
 1.3323677778244019,
 1.4481124877929688,
 1.441239595413208,
 1.4646072387695312,
 1.4027187824249268,
 1.3859988451004028,
 1.309499740600586,
 1.2216029167175293,
 1.1615114212036133,
 1.1226389408111572,
 1.0554890632629395,
 0.989854097366333,
 1.000708818435669,
 1.1687757968902588,
 1.250861644744873,
 1.3032331466674805,
 1.2706007957458496,
 1.2049438953399658,
 1.1479706764221191,
 1.0879448652267456,
 1.0093622207641602,
 0.9580950736999512,
 0.8625385761260986,
 0.8338674306869507,
 0.7963849902153015,
 0.7840545177459717,
 0.7324529886245728,
 0.7412367463111877,
 0.7125685214996338,
 0.7356940507888794,
 0.768915057182312,
 0.7581443190574646,
 0.7520101070404053,
 0.7311397790908813,
 0.7123045325279236,
 0.7537842988967896,
 0.7546627521514893,
 0.8060493469238281,
 0.8461723327636719,
 0.9376167058944702,
 1.0379199981689453,
 1.1446690559387207,
 1.125624418258667,
 1.1123709678649902,
 1.09669828414917,
 1.0267255306243896,
 1.0166475772857666,
 1.010796308517456,
 1.028071403503418,
 1.0508253574371338,
 1.1062827110290527,
 1.0697102546691895,
 0.978763222694397,
 0.9554329514503479,
 1.066009521484375,
 1.1249229907989502,
 1.2009735107421875,
 1.2161716222763062,
 1.230088233947754,
 1.1798408031463623,
 1.1651581525802612,
 1.1309975385665894,
 1.0950927734375,
 1.0468002557754517,
 1.01983642578125,
 0.984679102897644,
 0.9557101726531982,
 0.936781644821167,
 0.8602045774459839,
 0.8628756999969482,
 0.878974437713623,
 0.8961985111236572,
 0.9252946376800537,
 0.9644228219985962,
 1.0273919105529785,
 1.2373831272125244,
 1.2189788818359375,
 1.224463701248169,
 1.1476802825927734,
 1.039966344833374,
 1.0585145950317383,
 1.2366304397583008,
 1.5190989971160889,
 1.8925429582595825,
 2.0408053398132324,
 2.0061776638031006,
 1.903405785560608,
 1.9563641548156738,
 2.059500217437744,
 2.18212890625,
 2.0020370483398438,
 1.6339088678359985,
 1.2821040153503418,
 1.0439321994781494,
 1.0018978118896484,
 1.078251838684082,
 1.1365251541137695,
 1.1336190700531006,
 1.0832440853118896,
 1.02894926071167,
 0.9714642763137817,
 0.9505306482315063,
 0.9653599262237549,
 0.9673556089401245,
 1.0045323371887207,
 1.0885391235351562,
 1.1248915195465088,
 1.1600632667541504,
 1.2028651237487793,
 1.2494696378707886,
 1.1904997825622559,
 1.129112720489502,
 0.9877164959907532,
 0.9005264043807983,
 0.8606532216072083,
 0.8286726474761963,
 0.8773548603057861,
 0.8509222865104675,
 0.8564746379852295,
 0.8391351699829102,
 0.8202059268951416,
 0.8361029028892517,
 0.8533254861831665,
 0.8821689486503601,
 0.8460099697113037,
 0.8277947902679443,
 0.8550620079040527,
 0.8365728855133057,
 0.8132107257843018,
 0.8170299530029297,
 0.802739143371582,
 0.8179820775985718,
 0.9084900617599487,
 1.1414382457733154,
 1.236067533493042,
 1.355747103691101,
 1.427436113357544,
 1.390647292137146,
 1.3474512100219727,
 1.2689366340637207,
 1.1022899150848389,
 0.968428373336792,
 0.8207661509513855,
 0.8172966241836548,
 0.771111011505127,
 0.8076919317245483,
 0.8792248964309692,
 0.8948690295219421,
 0.901929497718811,
 0.7951549887657166,
 0.7470928430557251,
 0.7238975167274475,
 0.7223628759384155,
 0.7482411861419678,
 0.7521289587020874,
 0.8239130973815918,
 0.8680834770202637,
 0.9141967296600342,
 0.9598074555397034,
 1.0317363739013672,
 1.058330774307251,
 1.0598045587539673,
 1.0262020826339722,
 1.0023210048675537,
 0.9982255697250366,
 0.9603714942932129,
 0.9249633550643921,
 0.8766322135925293,
 0.8687701225280762,
 0.8657425045967102,
 0.8404006361961365,
 0.8243982791900635,
 0.8151012659072876,
 0.8049359321594238,
 0.8222866654396057,
 0.8373414278030396,
 0.7544768452644348,
 0.7492434978485107,
 0.732105553150177,
 0.7314207553863525,
 0.7557319402694702,
 0.7688559293746948,
 0.8429090976715088,
 0.8602586984634399,
 0.8711426258087158,
 0.9178544282913208,
 1.0036523342132568,
 1.0565115213394165,
 1.0861196517944336,
 1.139780879020691,
 1.1073033809661865,
 1.0979914665222168,
 1.2114497423171997,
 1.2815654277801514,
 1.3976329565048218,
 1.431812047958374,
 1.3586394786834717,
 1.3196065425872803,
 1.3307011127471924,
 1.178469181060791,
 1.0796871185302734,
 1.0000375509262085,
 0.9495939016342163,
 0.9660192728042603,
 0.9345794916152954,
 0.8998150825500488,
 0.8873492479324341,
 0.8338949680328369,
 0.7832863926887512,
 0.7462570667266846,
 0.7770464420318604,
 0.7486995458602905,
 0.7288497686386108,
 0.6927252411842346,
 0.6526753902435303,
 0.6910235285758972,
 0.6953835487365723,
 0.7142705917358398,
 0.7205066680908203,
 0.7314262390136719,
 0.7225949764251709,
 0.6804458498954773,
 0.6830011606216431,
 0.6524850130081177,
 0.6507650017738342,
 0.6542762517929077,
 0.6599081754684448,
 0.6563845276832581,
 0.6572178602218628,
 0.6427785158157349,
 0.6508798599243164,
 0.6451480984687805,
 0.6620924472808838,
 0.6922075748443604,
 0.63814377784729,
 0.6206808090209961,
 0.6576727628707886,
 0.7130757570266724,
 0.7589565515518188,
 0.7979684472084045,
 0.8811472058296204,
 0.8586934804916382,
 0.9502345323562622,
 1.0492472648620605,
 1.176743745803833,
 1.176438570022583,
 1.0723516941070557,
 0.9613116979598999,
 0.8688886165618896,
 0.8358896970748901,
 0.8285852670669556,
 0.8591147065162659,
 0.861060619354248,
 0.9184740781784058,
 0.9341291189193726,
 0.9899977445602417,
 0.9519418478012085,
 0.9188382029533386,
 0.8351612091064453,
 0.7284383773803711,
 0.6934301853179932,
 0.6888819932937622,
 0.6786410212516785,
 0.6915215253829956,
 0.7228233814239502,
 0.7191004753112793,
 0.7029595375061035,
 0.7933681011199951,
 0.8613570332527161,
 0.8915509581565857,
 0.8555135726928711,
 0.8253054618835449,
 0.7418526411056519,
 0.7448102235794067,
 0.7108818292617798,
 0.663597583770752,
 0.658208966255188,
 0.6970664262771606,
 0.6919964551925659,
 0.7295777797698975,
 0.796549379825592,
 0.8535263538360596,
 0.9241387248039246,
 0.9288372993469238,
 1.0028800964355469,
 1.0472309589385986,
 1.1139826774597168,
 1.1312627792358398,
 1.156759262084961,
 1.2154370546340942,
 1.301389455795288,
 1.3800454139709473,
 1.4470605850219727,
 1.4930870532989502,
 1.5014184713363647,
 1.493950366973877,
 1.4864020347595215,
 1.5086030960083008,
 1.4366289377212524,
 1.4776687622070312,
 1.4757769107818604,
 1.4171420335769653,
 1.3767879009246826,
 1.329167127609253,
 1.2785730361938477,
 1.3026713132858276,
 1.3140368461608887,
 1.3035491704940796,
 1.2758827209472656,
 1.2541106939315796,
 1.1896142959594727,
 1.1004607677459717,
 1.055945873260498,
 0.9484326839447021,
 0.9058194160461426,
 0.8503714203834534,
 0.8088234663009644,
 0.7681398391723633,
 0.7805039882659912,
 0.8188174962997437,
 0.8585041761398315,
 0.8467613458633423,
 0.8469366431236267,
 0.8007290363311768,
 0.7665087580680847,
 0.7256544232368469,
 0.7277621030807495,
 0.7039293050765991,
 0.7234287858009338,
 0.7477008104324341,
 0.7857319116592407,
 0.779229998588562,
 0.7864061594009399,
 0.7798840999603271,
 0.7553406953811646,
 0.7518538236618042,
 0.8254286050796509,
 0.8926985263824463,
 1.0468835830688477,
 1.2927231788635254,
 1.5508887767791748,
 1.8098169565200806,
 1.936543345451355,
 1.8981196880340576,
 2.012117385864258,
 2.0333540439605713,
 2.052774667739868,
 1.8479341268539429,
 1.5134655237197876,
 1.1664917469024658,
 1.1105659008026123,
 1.3612313270568848,
 1.4496092796325684,
 1.4598109722137451,
 1.3638941049575806,
 1.14259672164917,
 1.075021505355835,
 0.959404468536377,
 0.8911694288253784,
 0.7921720743179321,
 0.7219685316085815,
 0.6651827692985535,
 0.6925755739212036,
 0.7858901023864746,
 0.7977117896080017,
 0.8303878307342529,
 0.7558713555335999,
 0.6780426502227783,
 0.6960651278495789,
 0.6438958048820496,
 0.6133377552032471,
 0.5876853466033936,
 0.5642567276954651,
 0.5809676647186279,
 0.5597598552703857,
 0.5979875922203064,
 0.5770323276519775,
 0.5993506908416748,
 0.6098402738571167,
 0.6003869771957397,
 0.6168673038482666,
 0.6128419637680054,
 0.671601414680481,
 0.7032418251037598,
 0.7551254034042358,
 0.8218079805374146,
 0.8708506226539612,
 0.8929634690284729,
 0.9709445238113403,
 1.0241167545318604,
 1.075424313545227,
 1.0664047002792358,
 0.9938401579856873,
 1.0277211666107178,
 1.0146849155426025,
 1.1019481420516968,
 1.2332353591918945,
 1.2861098051071167,
 1.341031789779663,
 1.393043041229248,
 1.4723310470581055,
 1.4775826930999756,
 1.4681978225708008,
 1.4277626276016235,
 1.3972657918930054,
 1.4203622341156006,
 1.4130306243896484,
 1.4949195384979248,
 1.5153512954711914,
 1.5329866409301758,
 1.5514707565307617,
 1.5662686824798584,
 1.5336946249008179,
 1.3597712516784668,
 1.1788990497589111,
 1.0165750980377197,
 0.9362504482269287,
 0.867764949798584,
 0.8722495436668396,
 0.9020726680755615,
 0.8988133668899536,
 0.8338791131973267,
 0.779924750328064,
 0.6915860176086426,
 0.6863549947738647,
 0.6769083738327026,
 0.6742560863494873,
 0.6839078664779663,
 0.7159608602523804,
 0.8937383890151978,
 1.0472841262817383,
 1.145757794380188,
 1.2178031206130981,
 1.0586512088775635,
 0.932314395904541,
 0.6850529909133911,
 0.601121187210083,
 0.5923210382461548,
 0.7049564719200134,
 0.7817339897155762,
 0.837630033493042,
 0.743465781211853,
 0.7803852558135986,
 0.7658336162567139,
 0.7941951751708984,
 0.8915660381317139,
 0.9601129293441772,
 1.0775434970855713,
 1.0725393295288086,
 1.0817217826843262,
 1.0830464363098145,
 1.097450852394104,
 1.180562138557434,
 1.2231513261795044,
 1.195008397102356,
 1.1151155233383179,
 0.9359273910522461,
 0.9217172265052795,
 0.9404802322387695,
 0.9734824895858765,
 0.976392388343811,
 0.9879275560379028,
 1.0325844287872314,
 1.0289764404296875,
 1.0257164239883423,
 1.0127339363098145,
 0.92626953125,
 0.8730155229568481,
 0.79866623878479,
 0.7416021227836609,
 0.7614455819129944,
 0.7886441946029663,
 0.8725281357765198,
 0.9254701137542725,
 0.9348889589309692,
 0.9103879928588867,
 0.9141406416893005,
 0.9508610963821411,
 1.0133318901062012,
 0.9987500309944153,
 0.9493817090988159,
 0.8602316379547119,
 0.7916052341461182,
 0.7143955230712891,
 0.6730083227157593,
 0.6907391548156738,
 0.696864128112793,
 0.7335288524627686,
 0.7016875743865967,
 0.7435058355331421,
 0.7555760145187378,
 0.7841466665267944,
 0.7827914953231812,
 0.7793222665786743,
 0.762089729309082,
 0.8121541738510132,
 0.846267580986023,
 1.0116932392120361,
 1.1502913236618042,
 1.169609785079956,
 1.1573610305786133,
 1.2917065620422363,
 1.425518274307251,
 1.4315185546875,
 1.4428799152374268,
 1.527848243713379,
 1.7665035724639893,
 2.078036069869995,
 2.373253345489502,
 2.4025278091430664,
 2.2350049018859863,
 1.9049179553985596,
 1.6536126136779785,
 1.313631534576416,
 1.0618116855621338,
 1.0647337436676025,
 1.1138781309127808,
 1.1447396278381348,
 1.1646865606307983,
 1.1852903366088867,
 1.1354873180389404,
 1.0927813053131104,
 1.0325649976730347,
 1.046598196029663,
 1.0338480472564697,
 1.0224792957305908,
 0.9961138963699341,
 0.977066159248352,
 1.02592134475708,
 1.0578020811080933,
 1.1406962871551514,
 1.267242431640625,
 1.1734027862548828,
 1.190738320350647,
 1.1712232828140259,
 1.2078912258148193,
 1.165903091430664,
 1.0801275968551636,
 1.0121285915374756,
 0.8932434320449829,
 0.7938194870948792,
 0.7996479868888855,
 0.8236409425735474,
 0.875091552734375,
 0.9173234701156616,
 0.9433502554893494,
 1.008133053779602,
 1.007382869720459,
 1.0374956130981445,
 1.124629259109497,
 1.0614757537841797,
 1.0335956811904907,
 0.9055964946746826,
 0.9981851577758789,
 1.299875259399414,
 1.6338050365447998,
 1.8252983093261719,
 1.6772127151489258,
 1.3023486137390137,
 0.9426535367965698,
 0.8505196571350098,
 0.9368481636047363,
 1.0294743776321411,
 1.130838394165039,
 1.1090015172958374,
 1.0056915283203125,
 0.9859548807144165,
 0.7881072759628296,
 0.746468186378479,
 0.7031850814819336,
 0.6699892282485962,
 0.7816287279129028,
 0.9849213361740112,
 1.34998619556427,
 1.5558769702911377,
 1.697890281677246,
 1.8962721824645996,
 2.065028190612793,
 2.1408984661102295,
 2.2120392322540283,
 2.131678581237793,
 2.090806484222412,
 1.906315565109253,
 1.6846572160720825,
 1.4803555011749268,
 1.338151216506958,
 1.165318250656128,
 0.9458142518997192,
 0.859809160232544,
 0.7755788564682007,
 0.767422080039978,
 0.7485347986221313,
 0.7956494092941284,
 0.7564004063606262,
 0.778572678565979,

In [10]:
d = [d[0] for d in ecc_dist]
err = [d[1] for d in ecc_dist]

TypeError: 'float' object is not subscriptable

In [14]:
# df = pd.DataFrame({"dist": d + [0.0], "err": err + [1.0], "frame1": frames})
df = pd.DataFrame({"dist": ecc_dist + [0.0], "frame1": frames})

In [15]:
df.to_pickle("/home/roman/ba/mercedes_ecc_homography2.pkl")

In [52]:
pkls = list(Path("/home/roman/ba/niederfuellbach2_autos/frame_distances").iterdir())

In [63]:
pd.read_pickle(pkls[0])

                                                   name    sharpness      dist
0     /home/roman/ba/niederfuellbach2_autos/frames/m...  1128.268878  1.378382
1     /home/roman/ba/niederfuellbach2_autos/frames/m...  1211.548382  1.344790
2     /home/roman/ba/niederfuellbach2_autos/frames/m...  1233.124155  1.235398
3     /home/roman/ba/niederfuellbach2_autos/frames/m...  1203.057104  1.520507
4     /home/roman/ba/niederfuellbach2_autos/frames/m...  1218.534970  1.992893
...                                                 ...          ...       ...
1735  /home/roman/ba/niederfuellbach2_autos/frames/m...  3975.626043  5.754722
1736  /home/roman/ba/niederfuellbach2_autos/frames/m...  4585.837999  7.408754
1737  /home/roman/ba/niederfuellbach2_autos/frames/m...  4454.864914  8.909838
1738  /home/roman/ba/niederfuellbach2_autos/frames/m...  4925.961714  9.152380
1739  /home/roman/ba/niederfuellbach2_autos/frames/m...  4679.715725  0.000000

[1392 rows x 3 columns]

In [73]:
for p in pkls:
    df = pd.read_pickle(p)
    if isinstance(df["dist"].values[0], tuple):
        print("Processing ", p)
        df["dist"] = df["dist"].apply(lambda x: x[0] if isinstance(x, tuple) else x)
    else:
        print("dist is not a tuple ", p)
    df = df.reset_index(drop=True)
    df.to_pickle(p)

dist is not a tuple  /home/roman/ba/niederfuellbach2_autos/frame_distances/mercedes_a_class_closeup_damage_frames_1_sdr.pkl
dist is not a tuple  /home/roman/ba/niederfuellbach2_autos/frame_distances/mercedes_a_class_closeup_damage2_frames_1_sdr.pkl
dist is not a tuple  /home/roman/ba/niederfuellbach2_autos/frame_distances/mercedes_a_class_closeup_damage3_frames_1_sdr.pkl
dist is not a tuple  /home/roman/ba/niederfuellbach2_autos/frame_distances/mercedes_a_class_orbit_frames_1_sdr.pkl
dist is not a tuple  /home/roman/ba/niederfuellbach2_autos/frame_distances/white_van_orbit_frames_1_sdr.pkl
dist is not a tuple  /home/roman/ba/niederfuellbach2_autos/frame_distances/yellow_van_closeup_damage_frames_1_sdr.pkl
dist is not a tuple  /home/roman/ba/niederfuellbach2_autos/frame_distances/yellow_van_closeup_damage2_frames_1_sdr.pkl
dist is not a tuple  /home/roman/ba/niederfuellbach2_autos/frame_distances/yellow_van_orbit_frames_1_sdr.pkl

In [74]:
dff = pd.read_pickle("/home/roman/ba/niederfuellbach2_autos/frame_distances/mercedes_a_class_closeup_damage2_frames_1_sdr.pkl")

In [78]:
dff["dist"]

0       2.379302
1       2.340890
2       2.267688
3       2.095264
4       1.880408
          ...
1323    5.692407
1324    5.854483
1325    5.699860
1326    5.343443
1327    4.857228
Name: dist, Length: 1328, dtype: float64

In [80]:
pd.to_numeric(dff["dist"], errors="coerce")

0       2.379302
1       2.340890
2       2.267688
3       2.095264
4       1.880408
          ...
1323    5.692407
1324    5.854483
1325    5.699860
1326    5.343443
1327    4.857228
Name: dist, Length: 1328, dtype: float64

In [50]:
dff

                                                   name    sharpness      dist
0     /home/roman/ba/niederfuellbach2_autos/frames/m...  3281.816895  2.379302
1     /home/roman/ba/niederfuellbach2_autos/frames/m...  3198.941683  2.340890
2     /home/roman/ba/niederfuellbach2_autos/frames/m...  3306.335809  2.267688
3     /home/roman/ba/niederfuellbach2_autos/frames/m...  3219.024172  2.095264
4     /home/roman/ba/niederfuellbach2_autos/frames/m...  3349.150118  1.880408
...                                                 ...          ...       ...
1626  /home/roman/ba/niederfuellbach2_autos/frames/m...  1715.278304  5.692407
1627  /home/roman/ba/niederfuellbach2_autos/frames/m...  1661.700856  5.854483
1628  /home/roman/ba/niederfuellbach2_autos/frames/m...  1666.152493  5.699860
1629  /home/roman/ba/niederfuellbach2_autos/frames/m...  1383.083551  5.343443
1630  /home/roman/ba/niederfuellbach2_autos/frames/m...  1335.413953  4.857228

[1328 rows x 3 columns]